from typing import Protocol


class Stats(Protocol):
    def count_annihilation(self) -> None: ...
    def count_commute(self) -> None: ...
    def count_copy(self) -> None: ...
    def count_erase(self) -> None: ...
    def count_expand(self) -> None: ...
    def count_call(self) -> None: ...
    def count_branch(self) -> None: ...
    def count_alloc(self) -> None: ...
    def count_heap(self) -> None: ...
    def count_free(self) -> None: ...
    def measure_heap(self) -> None: ...
